apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - secretproviderclass.yaml
images:
  - name: backend
    newName: PLACEHOLDER_ECR/backend
    newTag: v0.0.0-placeholder
