apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-analysis
  namespace: argocd
spec:
  project: platform-foundry
  source:
    repoURL: https://github.com/aryn-lacy/platform-foundry.git
    targetRevision: main
    path: k8s/analysis/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
