apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - app-backend.yaml
  - app-frontend.yaml
  - app-keycloak.yaml
  - app-bootstrap.yaml
  - app-analysis.yaml
