apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak
  namespace: keycloak
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "platform-foundry/PLACEHOLDER_ENV/keycloak-db"
        type: secretsmanager
        jmesPath:
          - path: username
            objectAlias: dbuser
          - path: password
            objectAlias: dbpassword
          - path: host
            objectAlias: dbhost
          - path: dbname
            objectAlias: dbname
      - objectName: "platform-foundry/PLACEHOLDER_ENV/keycloak-admin"
        type: secretsmanager
        jmesPath:
          - path: username
            objectAlias: adminuser
          - path: password
            objectAlias: adminpassword
  secretObjects:
    - secretName: keycloak-db
      type: Opaque
      data:
        - key: username
          objectRef: dbuser
        - key: password
          objectRef: dbpassword
        - key: host
          objectRef: dbhost
        - key: dbname
          objectRef: dbname
    - secretName: keycloak-admin
      type: Opaque
      data:
        - key: username
          objectRef: adminuser
        - key: password
          objectRef: adminpassword
  volumeMount:
    - name: secrets
      mountPath: /mnt/secrets/keycloak
      readOnly: true
